
struct ALO {
    //struct LO field0_0x0;
    //struct DL dlChild;
    //struct DLE dleBusy;
    //struct DLE dleMRD;
    //struct ALO* paloRoot;
    struct ALO* paloFreezeRoot;
    //struct DLE dleFreeze;
    //struct DL dlFreeze;
    int cpmrg;
    struct MRG* apmrg[4];
    float sMRD;
    float sCelBorderMRD;
    int grfzon;
    float dsMRDSnap;
    //struct FRZ frz;
    //struct XF xf;
    //struct VECTOR posOrig;
    //struct MATRIX3 matOrig;
    //struct VECTOR eulOrig;
    //struct DL dlAct;
    struct ACT* pactPos;
    struct ACT* pactRot;
    struct ACT* pactScale;
    struct ACT** apactPose;
    struct ACT* pactRestore;
    struct ACTLA* pactla;
    struct ACTBANK* pactbank;
    struct IKH* pikh;
    struct CLQ* pclqPosSpring;
    struct CLQ* pclqPosDamping;
    struct CLQ* pclqRotSpring;
    struct CLQ* pclqRotDamping;
    struct SMPA* psmpaPos;
    struct SMPA* psmpaRot;
    struct ALOX* palox;
    int cframeStatic;
    //struct GLOBSET globset;
    struct SHADOW* pshadow;
    struct THROB* pthrob;
    float sFastShadowRadius;
    float sFastShadowDepth;
    int fRealClock;
    struct FADER* pfader;
    float dtUpdatePause;
    struct ASEGD* pasegd;
    float sRadiusRenderSelf;
    float sRadiusRenderAll;
    struct SFX* psfx;
    //struct FICG ficg;
    int cposec;
    struct POSEC* aposec;
    struct ACTREF* pactrefCombo;
    struct DLR* pdlrFirst;
    enum ACK ackRot;
};