name: Build project and validate checksum

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  build:
    if: github.repository_owner == 'theonlyzac'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup build environment
        run: |
          scripts/quickstart.sh
          curl -o disc/SCUS_971.98 "${{ secrets.FILE_URL }}"

      - name: Run build script
        run: scripts/build.sh
