name: Post mapfile_parser progress to Frogress endpoint

on:
  push:
    branches:
      - main
      - progress

jobs:
  frogress-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          scripts/quickstart.sh
          curl -o disc/SCUS_971.98 "${{ secrets.FILE_URL }}"

      - name: Run build script
        run: scripts/build.sh

      - name: Post to frogress endpoint
        run: |
          python3 scripts/frogress/upload_progress.py --frogress_api_key ${{ secrets.FROGRESS_API_KEY }}
