name: Upload objdiff report for Decomp.dev bot

on:
  push:
    branches:
      - main
      - progress

jobs:
  report-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          scripts/quickstart.sh
          curl -o disc/SCUS_971.98 "${{ secrets.FILE_URL }}"
          
      - name: Activate venv
        run: echo "${{ github.workspace }}/env/bin" >> $GITHUB_PATH

      - name: Configure and generate report
        run: |
          python configure.py --objects
          ninja
          ./tools/objdiff/objdiff-cli report generate > report.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SCUS_971.98_report
          path: ./report.json
